language: python
python:
  - "2.7"
  - "3.6"

os:
  - linux

install: pip install -r requirements.txt
script: python test/run

after_success:
 - pip install pyflakes
 - pyflakes tasks/*.py | tee >(wc -l)
 - pyflakes test/*.py  | tee >(wc -l)
 - pyflakes run        | tee >(wc -l)

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.6
